# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $HOME/.functions.sh
source $HOME/.nvm.sh # should be before exports as we use yarn there
source $HOME/.exports.sh
source $HOME/.antigen.sh
source $HOME/.aliases.sh
source ~/.iterm2_shell_integration.zsh
eval "$(direnv hook zsh)" # Direnv hook

# ZSH options
unsetopt inc_append_history # Do not share shell history between sessions
unsetopt share_history

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
