ZSH_ENABLE_PROFILING=false

# Enable profiling if ZSH_PROFILE is set
if $ZSH_ENABLE_PROFILING; then
  zmodload zsh/zprof
fi

source $HOME/.functions.sh
source $HOME/.exports.sh
source $HOME/.antidote.sh
source $HOME/.node.sh
source $HOME/.aliases.sh
source ~/.iterm2_shell_integration.zsh
eval "$(direnv hook zsh)" # Direnv hook
eval "$(navi widget zsh)" # Navi shell widget, it is assigned to Ctrl+G
eval "$(starship init zsh)" 

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

# Enable completions
autoload -Uz compinit
compinit -d ~/.zcompdump

# ZSH options
unsetopt inc_append_history # Do not share shell history between sessions
unsetopt share_history

if $ZSH_ENABLE_PROFILING; then
  zprof
fi
