#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Collect packages lists
function backup {
  einf "Creating brew bundle"
  brew bundle dump --file="$BREW_BUNDLE_FILE" --force

  einf "Collecting vscode extensions list"
  code --list-extensions > "$CODE_PACKAGES"
}

askdo backup "Collecte brew bundle and vscode lists?"
