#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Install brew bundle
function install_brew_bundle {
  ensure_brew
  sudokeepalive

  einf "Updating brew"
  brew update

  einf "Installing brew bundle (taps & casks & brews & apps)"
  brew bundle --file "$BREW_BUNDLE_FILE"

  reload_shell
}

askdo install_brew_bundle "Install brew bundle?"
