#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_brew {
  if type "brew" > /dev/null; then
    einf "Brew already installed... skipping"
    return
  fi

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  if is_m1_mac; then
    echo "export PATH=/opt/homebrew/bin:$PATH" >> ~/.zshrc
    source ~/.zshrc
  fi

  # echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/psdcoder/.zprofile
  # eval "$(/opt/homebrew/bin/brew shellenv)"
  if ! type "brew" > /dev/null; then
    eerr "Brew failed to install"; exit 1
  fi

  einf "Brew installed successfully"

  if is_m1_mac; then sudo softwareupdate --install-rosetta; fi
}

askdo install_brew "Install brew?"
