#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Install xcode dev tools
function install_xcode_devtools {
  if xcode-select -p &> /dev/null; then
    einf "Xcode developer tools is already installed... skipping"
    return
  fi

  xcode-select --install
}

askdo install_xcode_devtools "Install xcode tools?"
