#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_brew {
  if type "brew" > /dev/null; then
    einf "Brew already installed... skipping"
    return
  fi

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

askdo install_brew "Install brew?"
