#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_apps {
  if ! type "mas" > /dev/null; then
    eerr "mas must be installed first from the brew..."; exit 1
  fi

  einf "Installing AppStore apps"
  cat $APP_STORE_APPS | cut -d'#' -f1 | \
  while read APP; do
    printf "Installing app with ID: $APP... "
    mas install $APP
  done

}

askdo install_apps "Install AppStore apps?"
