#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_managers {
  if type "nvm" > /dev/null 2>&1; then
    printf "nvm already installed... skipping\n"
  else
    einf "Installing nvm"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  fi
}

askdo install_managers "Install managers (nvm)?"
