#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Install rosetta
function install_rosetta {
  if is_m1_mac;then
    sudo softwareupdate --install-rosetta
  fi
}

askdo install_rosetta "Install rosetta?"
