#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Install brew
function setup_os {
  einf "Configuring macOS"
  sudokeepalive
  sh $DOTFILES_SHELL/macos

  einf "Now you can realod your shell"
}

askdo setup_os "Setup os?"
