#!/bin/zsh

# import helpers
source `dirname $0`/helpers

# Setup macOS preferences
function setup_os {
  einf "Configuring macOS system preferences"
  sudokeepalive
  sh $DOTFILES_SHELL/macos

  einf "macOS configuration complete!"
  ewrn "Some changes require logout/restart to take effect"
}

askdo setup_os "Setup os?"
