#!/bin/zsh

# import helpers
source `dirname $0`/helpers

function setup_node {
  if [ ! type "fnm" > /dev/null 2>&1 ]; then
    err "FNM must be installed first..."; exit 1
  fi


  einf "Installing latest FNM node"
  fnm install --lts

  if ! type "pnpm" > /dev/null 2>&1; then
    einf "Installing pnpm"
    corepack install -g pnpm
  else
    printf "pnpm already installed... skipping\n"
  fi

  einf "Installing global NPM packages"
  cat $NPM_PACKAGES | \
  while read PACKAGE; do
    printf "Installing $PACKAGE... "
    pnpm add -g $PACKAGE
  done
}

askdo setup_node "Setup node installation?"
