#!/bin/bash

# source helpers file
source `dirname $0`/helpers

# Install brew
function uninstall_env {
  einf "Unlinking shell configs"
  rm -f ~/.functions.sh
  rm -f ~/.exports.sh
  rm -f ~/.aliases.sh
  rm -f ~/.antigen.sh
  rm -f ~/.nvm.sh
  rm -f ~/.profile
  rm -f ~/.zshrc
  rm -f ~/.p10k.zsh

  einf "Unlinking editor configs"
  rm -f $HOME/Library/Application\ Support/Code/User/settings.json

  einf "Unlinking github configs"
  rm -f ~/.gitconfig
  rm -f ~/.gitignore
}

askdo uninstall_env "Unlink environment files?"
